### PR TITLE
Provide message for users when checking MetaMask

### LINKED ISSUE #18: Not showing an information message when Metamask is not connected
If I open the project website and I don't have my Metamask wallet connected, **the main screen is empty and doesn't show any message about why it's empty**.

Sometimes I don't have my wallet connected and I think that there is an error...after a while I realize that :( 

Example:
image

### PR DESCRIPTION
**Pull request by W3stside**
Fixes #18

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr28--dxservicesadmin.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr28--dxservicesadmin.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr28--dxservicesadmin.review.gnosisdev.com

**Comment by luarx** [comment]
Great! Thank you

**Pull request merged**
