### PR TITLE
Feature/mgn holders

### PR DESCRIPTION
**Pull request by anxolin**
Adds a new page with the MGN holders

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr31--dxservicesadmin.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr31--dxservicesadmin.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr31--dxservicesadmin.review.gnosisdev.com

**Review by W3stside — APPROVED** [review]
cool beanz

**Comment by anxolin** [comment]
Nice!

**Pull request merged**
